spring:
  data:
    mongodb:
      database: testdb

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.11

jwt:
  secret: "test-secret-key-which-is-at-least-32-characters-long!!"
  expiration: 86400000

openai:
  api:
    key: "test-openai-key"